### ISSUE TITLE
When does parse_dot return error?

### ISSUE THREAD

**Issue by Avi-D-coder** [magiclen/path-dedot#1]
A function that returned error if it escapes the root would also be useful.

"../" == Err
"a/../../" == Err
"a/../" = Ok(_)

**Comment by magiclen** [comment]
Getting the CWD may return an error. But currently I am using the `lazy_static` crate to cache the CWD (just unwrapping the result of env::current_dir()), because I am doubting we can encounter a practical case which leads to an invalid result.

I believe the paths you listed are all valid because the bash shell accepts this command,

```bash
cd / && cd ../
```

In other words, the path `../` is valid, so the dots in it can be parsed.

Could you give more specific cases to explain why you think preventing the path from escaping the root is more useful?
