### ISSUE TITLE
dedot_lv0_2 test is flaky

### ISSUE THREAD

**Issue by sharkdp** [magiclen/path-dedot#4]
I see spurious test failures when running the tests multiple times (and with high parallelism?):
```
❯ cargo test --release -j 20
    Finished release [optimized] target(s) in 0.00s
     Running /home/shark/.cargo-target/release/deps/path_dedot-80d51a965eea4b75

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running /home/shark/.cargo-target/release/deps/unix-b3483a1988d94c5d

running 8 tests
test dedot_lv0_1 ... ok
test dedot_after_updating_cwd ... ok
test dedot_lv1 ... ok
test dedot_lv2 ... ok
test dedot_lv0_2 ... FAILED
test dedot_lv3 ... ok
test dedot_lv4 ... ok
test dedot_lv5 ... ok

failures:

---- dedot_lv0_2 stdout ----
thread 'dedot_lv0_2' panicked at 'assertion failed: `(left == right)`
  left: `"/tmp/path/to/123/456"`,
 right: `"/path/to/123/456"`', tests/unix.rs:32:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    dedot_lv0_2

test result: FAILED. 7 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test unix'
```

**Comment by sharkdp** [comment]
Oh, sorry. It only seems to fail if I remove the `#[ignore]` line from the `dedot_after_updating_cwd` test. I was wondering why that was there...

**Comment by magiclen** [comment]
In order to not fetch the CWD (by using `env::current_dir().unwrap()`) on every operation, this crate caches the CWD. However, some usage might need to change the CWD #2, so I came up with a way to update it very unsafely (just by accessing a static variable directly). I assumed programmers to deal with the data racing problem by themselves (outside this crate) but it was not documented clearly and easy to go wrong even for me.

After @ignatenkobrain reported #3, I decided to fix the potential data racing problem inside this crate via an `AtomicBool` as a simple lock to let the update not be run simultaneously.

As for the `dedot_after_updating_cwd` test, because it uses `env::set_current_dir` to reset the CWD, and calls the `path_dedot::update_cwd` function to update the cache, it will lead to the results of other tests changes if it runs before them. That's why it should be ignored to be separated from other tests.

**Comment by sharkdp** [comment]
Thank you for the explanation.

Is it really necessary to cache the `env::current_dir()`? Did you perform some benchmarks with the new lock mechanism? Is it actually faster when cached?

Instead of building a custom lock mechanism with `unsafe` code, you could probably use something like `Arc<Mutex<CWD>>` or just `Mutex<CWD>` (and get rid of the `Rc<…>` layer?) and get rid of the unsafe parts.

**Comment by magiclen** [comment]
Caching the CWD (without locks) is definitely faster than calling `env::current_dir().unwrap()` every time. But with a `Rc` pointer, it's hard to tell (needs to be benchmarked).

I think `Mutex` is too heavy to be used for this case. Even for a single-thread situation, I have run some benchmarks before, the time overhead of a `Mutex` is about four times larger than an atomic operation on x86_64 arch.

**Comment by magiclen** [comment]
After running benchmarks for cache with a `Rc` pointer, I found the execution time (~700 ns for `parse_dot`) is twice longer than before (~350 ns for `parse_dot`). And it almost the same as the execution time calling `env::current_dir().unwrap()` every time.

Maybe we can just get rid of cache by default, but adding a new feature to enable the old cache mechanism (without locks and `Rc`) if needed.

**Comment by ignatenkobrain** [comment]
This would be the best I think.

**Comment by magiclen** [comment]
The modifications have been completed.
